spring.application.name=content-calender
spring.h2.console.enabled=true
spring.datasource.generate-unique-name=false
spring.datasource.name=content
logging.level.org.springframework.jdbc=DEBUG

# --- PostgreSQL Connection ---
#spring.datasource.url=jdbc:postgresql://localhost:5432/content_db
#spring.datasource.username=postgres
#spring.datasource.password=
#
## --- JPA Settings ---
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


